/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dms_miniproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Properties;
import java.util.Date;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
/**
 *
 * @author praty
 */
public class shop extends javax.swing.JFrame {

    /**
     * Creates new form shop
     */
    public shop() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chair = new javax.swing.JCheckBox();
        sofa = new javax.swing.JCheckBox();
        bed = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        squantity = new javax.swing.JTextField();
        cquantity = new javax.swing.JTextField();
        bquantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        scolour = new javax.swing.JTextField();
        ccolour = new javax.swing.JTextField();
        bcolour = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        m = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chair.setText("Chair");
        chair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chairActionPerformed(evt);
            }
        });
        getContentPane().add(chair, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        sofa.setText("Sofa");
        getContentPane().add(sofa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        bed.setText("Bed");
        getContentPane().add(bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel1.setText("Type");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel2.setText("Quantity");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));
        getContentPane().add(squantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 40, -1));
        getContentPane().add(cquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 40, -1));
        getContentPane().add(bquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 40, -1));

        jLabel3.setText("Colour Preference");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 100, -1));
        getContentPane().add(scolour, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 60, -1));
        getContentPane().add(ccolour, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 60, -1));
        getContentPane().add(bcolour, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 60, -1));

        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 80, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 90, 30));

        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 30));

        jLabel6.setText("Mob number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 90, 30));

        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 240, -1));

        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 240, -1));
        getContentPane().add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 240, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home h = new home(); 
        h.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void chairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int amount1=0;
        int amount2=0;
        int amount3=0;
        int amount =0;
        String type="";
        String type1 = "";
        String type2 = "";
        String type3 = "";
        if(chair.isSelected()){
            amount1 = 5000* Integer.parseInt(cquantity.getText());
            type1 = "Chair : "+ ccolour.getText();
        }
        if(sofa.isSelected()){
            amount2 = 10000* Integer.parseInt(squantity.getText());
            type2 = "Sofa : "+ scolour.getText();
        }
        if(bed.isSelected()){
            amount3 = 15000* Integer.parseInt(bquantity.getText());
            type3 = "Bed : "+ bcolour.getText();
        }
        amount = amount1+amount2+amount3;
        type = type1+type2+type3;
        PreparedStatement pst = null;
        PreparedStatement pst2 = null;
        Connection connector = null;
        display d = new display();
        try{
            
            DriverManager.registerDriver(new org.postgresql.Driver());
            String url = "jdbc:postgresql://localhost:5432/exp";
            Properties parameters = new Properties();
            parameters.put("user", "postgres");
            parameters.put("password", "root");
            connector = DriverManager.getConnection(url, parameters);
            pst = connector.prepareStatement("insert into \"public\".orders(type,time,price) values(?,?,?)");
            pst.setString(1,type);
            Date currentdate = new Date();
            SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
            pst.setString(2,dateformat.format(currentdate));
            pst.setLong(3, amount);
            
            /*pst2 = connector.prepareStatement("select name,address,mobnumber from \"public\".customer,\"public\".orders where orders.order_id = customer.customer_id");
            ResultSet rs = pst2.executeQuery();
            
            if (rs.next()){
                String n =rs.getString(1);
                d.n.setText(n);
                d.a.setText(rs.getString(2));
                d.m.setText(Long.toString(rs.getLong(3)));
            }*/
            
            d.n.setEditable(false);
            d.a.setEditable(false);
            d.m.setEditable(false);
            d.o.setEditable(false);
            d.amt.setEditable(false);
            
            d.n.setText(n.getText());
            d.a.setText(a.getText());
            d.m.setText(m.getText());
            d.o.setText(type);
            d.amt.setText(Integer.toString(amount));
            
            
            int r = pst.executeUpdate();
            pst.close();
           
            connector.close();
            
}catch(SQLException e){ System.out.println("ERROR"+ e); }
        
        d.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField a;
    private javax.swing.JTextField bcolour;
    private javax.swing.JCheckBox bed;
    private javax.swing.JTextField bquantity;
    private javax.swing.JTextField ccolour;
    private javax.swing.JCheckBox chair;
    private javax.swing.JTextField cquantity;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JTextField m;
    public javax.swing.JTextField n;
    private javax.swing.JTextField scolour;
    private javax.swing.JCheckBox sofa;
    private javax.swing.JTextField squantity;
    // End of variables declaration//GEN-END:variables
}
